# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import Code


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 380)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 320, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 320, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 320, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 191, 271))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(220, 40, 191, 271))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(420, 40, 191, 271))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(26, 9, 181, 31))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 9, 191, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(420, 10, 191, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Прописывание связь с действиями при нажатии кнопок
        self.pushButton.clicked.connect(self.Codirovka)
        self.pushButton_2.clicked.connect(self.Decodirovka)
        self.pushButton_3.clicked.connect(self.Cleaning)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Код Хэмминга"))
        self.pushButton.setText(_translate("Dialog", "Закодировать"))
        self.pushButton_2.setText(_translate("Dialog", "Декодировать"))
        self.pushButton_3.setText(_translate("Dialog", "Очистить"))
        self.label.setText(_translate("Dialog", "Текст"))
        self.label_2.setText(_translate("Dialog", "Закодированный текст"))
        self.label_3.setText(_translate("Dialog", "Вывод"))

    # Действия кнопок
    def Codirovka(self):
        textboxValue = self.textEdit.toPlainText()
        self.textEdit_3.append(Code.Coding(textboxValue))
    def Decodirovka(self):
        textboxValue_2 = self.textEdit_2.toPlainText()
        self.textEdit_3.append(Code.Decoding(textboxValue_2))
    def Cleaning(self):
        self.textEdit.clear()
        self.textEdit_2.clear()
        self.textEdit_3.clear()

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
